name: Test

on:
  [push]

jobs:
  code_stability_test:
    runs-on: ubuntu-latest
    name: Code stability test. Run analyzer against our own code.
    steps:
      - name: Inclusiveness Analyzer action step
        id: analyzer
        uses: ./