name: Test

on:
  push:
  workflow_dispatch:

jobs:
  code_stability_test:
    runs-on: ubuntu-latest
    name: Code stability test. Run analyzer against our own code.
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: npm install
      - name: Rebuild the dist directory
        run: npm run prepare
      - name: Inclusiveness Analyzer action step
        id: analyzer
        uses: ./
        with:
          excludeFromScan: '**/node_modules/**,**/dist/**,**/src/data.json,**/package.json'
          excludeUnchangedFiles: 'false'
